### PR TITLE
Typescript declaration support

### LINKED ISSUE #2: TypeScript Support
**This issue is related to a feature request**. It would be nice to have a definition type (at least) for VSCode Intellisense to trigger without having to go to the GitHub page (when using it, people will still go here to follow the installation instructions and get more informations of course).

It would be even greater if the code was written in TypeScript (but that is not necessary as an `index.d.ts` is enough with `{ "types": "./index.d.ts" }` in `package.json` in order to trigger the Intellisense).

**The solution I would like to be implemented** should follow these guidelines:
- A `index.d.ts` at the root of this project with the necessary [declaration instruction](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) related to TypeScript.
- A `"types"` key in the `package.json` with the value of `"index.d.ts"` (or the path to that file if it is in a directory) for VSCode & TypeScript Intellisense to trigger automatically.

**Alternatives** would be to create a package and push the type definition file to `@types/rollup-plugin-delete`. I am not a big fan of that solution as it may require to maintain an entire new repository (I guess, never had the opportunity to try) and it seems a little overkill to have to use `npm install --save-dev rollup-plugin-delete @types/rollup-plugin-delete` since the type definition file should not be large.

**Another alternative** would be to (re?)write the project using TypeScript. Since TypeScript is just a superset of JavaScript, this should not be hard to implement and would probably only require the adding of types to function parameters and variables.

### PR DESCRIPTION
**Pull request by aminnairi**
Closes #2 with hopefully enough help for TypeScript & VSCode users of the plugin.

### CODE REVIEW

**Comment by aminnairi** [comment]
@vladshcherbin changes have been made. Waiting for your review.

The `...rest` parameter has been added but I can't maintain a custom type for all glob options. Plus, TypeScript does not allow the use of the rest parameter in the type declaration so this is a nogo but not a big deal as it is obvious that this function can accept more (people will have to use the documentation on your GitHub page for more informations though).

For the return type, seems like Rollup has its own typing for plugins which is `Plugins`.

**Comment by vladshcherbin** [comment]
@aminnairi I'm not sure where or how external types are declared, maybe you have an example from another package, where they are declared as optionalDependencies or devDependencies to look at?

**Comment by vladshcherbin** [comment]
@aminnairi I quickly checked some packages, [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/package.json#L48) and [rollup-plugin-postcss-modules](https://github.com/flying-sheep/rollup-plugin-postcss-modules/blob/master/package.json#L20) use external types as `devDependencies`, maybe it's the way to go?

**Comment by aminnairi** [comment]
Why not, let's do this! I'll push when I'm done installing the development dependency and the module in the declaration file.

**Comment by vladshcherbin** [comment]
@aminnairi alright, I've read some stuff about TS and its ecosystem.

According to https://github.com/Microsoft/types-publisher/issues/81, dependencies which are used by the library and in declarations should go to `dependencies`, not in `devDependencies` - this way they will be automatically installed when library is used.

From the [typescript publishing docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) it's also said - If your package is not written in TypeScript then the second is the preferred approach, which is *publishing to the @types organization on npm*.

So, here my conclusion - I'm okay with typings file but I don't want to add `@types/del` package to dependencies so that *all* (both js/ts) users get them. The result is:

1) if I don't add `@types/del` to dependencies, in order to have typings you would need to use: `npm install rollup-plugin-delete @types/del`.
2) if published to `@types`, it would be possible to set `@types/del` as a dependency and in order to have typings you would need to use: `npm install rollup-plugin-delete @types/ollup-plugin-delete`

I'm not sure if currently there is a better way to deal with TS types. I find the second solution better because you install `package` and `@types/package` instead of random types.

What do you think?

**Comment by vladshcherbin** [comment]
I also checked, how to write types and checked `del` types. This should work:

```js
import del from 'del'
import { Plugin } from 'rollup'

export interface Options extends del.Options {
  targets: string[] | string,
  verbose?: boolean
}

export default function({ targets = [], verbose = false, ...rest }: Options): Plugin;
```

**Comment by aminnairi** [comment]
IMO the best way is to let the user deal with the `@types/rollup-plugin-delete` if they want and if they are using TypeScript (but VSCode users can use it anyway even if not using TypeScript).

I'm also thinking about making `@types/rollup-plugin-delete` an optional dependency (just to give the user the information that this package exist, I don't really know if there are any more advantages about the optional dependencies).

I didn't know we could extends interface. This makes it much easier for typings.

If we go with the DefinitelyTyped way, we can closed this pull request as all the processed is done when cloning the DefinitelyTyped repository. But this can take a few days. Not a big deal though.

**Comment by vladshcherbin** [comment]
@aminnairi yes, I think currently the best solution is to add `@types/rollup-plugin-delete` with all type dependencies it needs.

I've checked if any rollup plugin has typings there and found [rollup-plugin-node-resolve](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rollup-plugin-node-resolve) which gives me the feeling we are doing everything right.

I'm going to close this PR and I'll create a PR in `@types` tomorrow or the day after.

Thank you for this PR, nice conversation and getting familiar of what TS is 😉

**Pull request closed without merging**
